Patches for GPU implementation (#1)
* Update README.md

fixed typo's in readme

* Update helper.py

Fixed defaults referring to undefined xp.

* Update image3d.py

Fixes a typerror that occurs in the signal() constructor:

```
TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly. 
```

* Revert "Update helper.py"

This reverts commit 03ee8b19547515abc4faebd67a3dfd003223190a.

* re-added the changes to helper.py, as they did turn out to be necessary

* fix bug in image3d_test.py for move2gpu()

---------

Co-authored-by: Jonathan Stelter <jonathan.stelter@tum.de>